export const PUSH_TWOPANE_ELEMENT: string = 'PUSH_TWOPANE_ELEMENT';

export const REMOVE_KEY_TWOPANE_ELEMENT: string = 'REMOVE_KEY_TWOPANE_ELEMENT';

export const REPLACE_TWOPANE_ELEMENT: string = 'REPLACE_TWOPANE_ELEMENT';


